### ISSUE TITLE
Unclear descriptions of the models AvailabilityForDay and AvailabilityUpdateRecord

### ISSUE THREAD

**Issue by umran** [windingtree/wt-write-api#10]
I was just looking over the model specification as described [here](https://windingtree.github.io/docs/swagger-ui/) and I can't seem to figure out what AvailabilityForDay and AvalabilityUpdateRecord represent. My guess is that AvailabilityForDay is a record of on which days a particular unit is available. However, the description for the model is as follows: "Object where property names are roomTypeId", which implies that the availability information is listed by room type instead of by individual rooms. If this is so, what is the rationale? I would imagine that two different rooms of the same type could have different availability profiles and so listing availability by room type alone would be insufficient to encode that information.

Second, I have no clue what AvailabilityUpdateRecord represents. The description is: "Update to availability. Either total or change can be present, not both." - the total or change in what exactly?

A clarification would be highly appreciated. Thanks.

**Comment by JirkaChadima** [comment]
Thanks for your feedback! The `Availability` part of the model is still truly just a draft and will surely get more care before we will actually implement it. However, I will try to explain our reasoning a little bit more:

> AvailabilityForDay

- The data should be read as **for given roomType, on given day, I have `quantity` rooms of that roomType available with the following restrictions**
- We're not (yet?) modelling inventory on a room level, however you can say that you have only one room of each roomType, thus effectively doing an inventory on a room level. The `quantity` attribute for each day could then be either 0 or 1.
- Could you be more specific about different availability profiles? Our thinking was that the rooms of the same type are totally interchangeable.

> AvailabilityUpdateRecord

In some use cases, changing the whole `AvailabilitySnapshot` might take a lot of time and users could run into race conditions. That's why we came up with `AvailabilityUpdateRecord` which should be considered as a result of some event (typically booking) that changes the availability data. The `total` and `change` refer to `AvailabilityUpdateRecord`s atttribute that hold the quantity that should be used for given day. And the quantity can either be set absolutely (let's say you're closing the whole floor for some reason), or relatively (typically after a booking). The reasoning for this is that it might be more efficient to compute changes over larger periods of time.

Maybe @czervenka can add something more.

**Comment by umran** [comment]
HI

**Comment by umran** [comment]
@JirkaChadima Thanks for the prompt response. I now understand more fully the purpose of AvailabilityForDay. I understand that under this model, we would be able to know if a particular type of room would be available for a given list of days. However, the obvious drawback is that we can't keep track of the availability of a particular room for x consecutive days. Consider the following scenario.
Suppose there are 2 rooms, A and B of type T. Let A be available from week 1 to week 2, and let B be available from week 2 to week 3. The current model would report that a room of type T is available from week 1 to week 3, but it wouldn't be the same room that is available throughout the entire duration. This would have the consequence to a potential guest of having to change rooms mid-vacation. I think it would be nice to have the model report this technicality ahead of the booking.

Thanks also for your detailed explanation of AvailabilityUpdateRecord.

**Comment by JirkaChadima** [comment]
Yes, we're aware of this drawback and weren't able to yet find a suitable solution. It's still a good point though and I've added it to our TODO list. If we want to report this kind of data, it has potentially some implications into the inventory model (roomTypes definition).

For now, the only solution I can see is to ignore the concept of roomTypes altogether, and have a separate roomType for each room.

**Comment by JirkaChadima** [comment]
Well, to keep things consistent, you would have to store a list of for example room numbers or something like that. And then you might want to differentiate rooms by other attributes, I can see a different pricing for different rooms... It just might be hard to figure out where to draw the line. But nothing is set in stone, we're definitely thinking about it. Maybe we'll extend the model later.

**Comment by umran** [comment]
Thanks for your time. Much appreciated.
