### ISSUE TITLE
Does Winding Tree provide any assurances of the continued integrity of data stored offchain?

### ISSUE THREAD

**Issue by umran** [windingtree/wt-write-api#56]
This is probably not the best place to ask a protocol specific question, however I came to be aware of this issue while going over the write api, specifically the hotel update method, so it is perhaps appropriate for me to raise the issue here. I apologize in advance if there is a more appropriate place for this question.

To jump straight into my point, I noticed that while updating hotel fields that have a pointer to an external resource, it is possible that the updated resource URI stays the same as the original URI. Since the WT index only has a record of the resource URIs I'm just concerned that there might not be a reliable way of keeping track of the updates. This is a concern because it has the potential to create disputes between suppliers and consumers. For example, a hotel might change the information advertised about available amenities for a room that is already booked and if the updated information points to the same URI, there might not be a way of tracking the change from the wt index directly, which I assume is the single source of truth regarding bookings and hotel information. This would not be a problem if the advertised information about a particular room is locked in at the time of booking. For example a hash of all the room details may be stored along with the booking record on the WT index.

With that said, I haven't had the time to look into the entire Winding Tree protocol so it's entirely possible that the issue is mitigated in either a manner similar to what I have mentioned or an entirely different method. If that is the case, I hope someone can explain to me how it is implemented. It is also possible that Winding Tree is not designed to give assurances on the continued integrity of hotel information, in which case it is not what i imagined it to be. In any case thanks for taking the time to hear out my concern.

**Comment by JirkaChadima** [comment]
Thanks for an excellent question, a better place for discussion of this general kind would probably be our [mailing list](https://groups.google.com/forum/#!forum/windingtree). But since we're already here...

Let me start with some axioms about WT platform:
- We do not force anybody to use any particular kind of off-chain storage.
- We do not force anybody to use any piece of software we have written.

These two things bring a few implications regarding data integrity and assurances about that.

1. Every off-chain storage has different properties regarding the mutability of the data. WT platform users have to decide what they want to use:

    - Fast updates - mutable data with stable identifiers (typically HTTP, potentially Swarm Feeds)
    - Slower updates - immutable data with the need of changing the address on-chain after every change. (Swarm or IPFS)
    - Something else with different properties?

2. For keeping track of changes, we have created the [Notification API](/windingtree/wt-notification-api), but we are not forcing anyone to use it to propagate data changes to everybody. But we believe the majority of our data producers will use it because it will bring a superior service to their clients.

So, yes, under certain conditions, it is possible that the data changes under the same identifier and nobody will notice. We have thought about storing hierarchical hashes of the data to keep track of integrity, but for that to be totally reliable, we would have to store it on-chain, which is slow and expensive (on-chain transaction for every data change). Also, historical data might not be available anymore to settle a dispute. But it should not actually be a problem.

The advertised data itself (hotel metadata, availability, rate plans, amenities) can change at any time and that is why the first version of our [booking protocol](https://github.com/windingtree/wt-booking-api/blob/master/docs/swagger.yaml) contains computed price, cancellation terms etc. I'm pretty sure that we will have to add a full room type object there as well (but we don't have a concensus on that in the team, I personally think it should totally be there).

The idea behind that is, that you (consumer) are declaring an interest in booking such and such thing, and the hotel has to confirm that they agree with that. And you are not booking some room type identifier, you are booking a particular set of rooms, services, amenities and all that other stuff. This is/should be forming the actual contract between a hotel and the end-consumer which can be paid for. And that can easily be hashed and used for example as an identifier for payment or something like that.

Thank you for your comment, and I think that we are aiming to solve this issue in a similar way that you propose. I don't think we have a real timeline for addressing this in particular but I think we will deal with that organically when we need to.

**Comment by umran** [comment]
Thanks for the prompt response as always. I am glad that you and the team are aware of this issue.

I agree, on chain transactions for every data change is costly so that is not the most efficient solution. You capture my concern perfectly when you say that that the consumer is not booking some room type but rather a particular set of rooms, services, amenities, etc. As long as there is a way to indicate this information on chain regarding bookings there is no problem. Thanks again.
